project:
  type: website

website:
  title: "Posit Experiments"
  favicon: images/favicon.ico
  navbar:
    right:
      - text: Home
        href: index.qmd
      - about.qmd
      - icon: github
        href: https://github.com/SamEdwardes/posit-experiments
format:
  html:
    theme: litera
    css: styles.css



