project:
  type: website

website:
  title: "Posits"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/SamEdwardes/posits-blog
      - icon: twitter
        href: https://twitter.com/TheReaLSamlam
format:
  html:
    theme: litera
    css: styles.css



